version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeepery
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafkay
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeepery:2181